let customers = [
    {
        _id: "1",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 1",
        pdfs:"15",
        services: ["website", "social-media", "branding"],
        url: "www.gpofcu.org",
        status: "Signed",
        pm: "2",
        dev: "5",
        compliance: "1"
    },
    {
        _id: "2",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 2",
        pdfs:"15",
        services: ["website", "branding"],
        url: "www.gpofcu.org",
        status: "Signed",
        pm: "2",
        dev: "5",
        compliance: "6"
    },
    {
        _id: "3",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 3",
        pdfs:"15",
        services: ["website", "social-media", "branding"],
        url: "www.gpofcu.org",
        status: "Signed",
        pm: "2",
        dev: "5",
        compliance: "6"
    },
    {
        _id: "4",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 4",
        pdfs:"15",
        services: ["website", "social-media", "branding"],
        url: "www.gpofcu.org",
        status: "Signed"
    },
    {
        _id: "5",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 5",
        pdfs:"15",
        services: ["website", "social-media", "branding"],
        url: "www.gpofcu.org",
        status: "Signed",
        pm: "2",
        dev: "5",
        compliance: "6"
    },
    {
        _id: "6",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 6",
        pdfs:"15",
        services: ["website", "social-media", "branding"],
        url: "www.gpofcu.org",
        status: "Signed",
        pm: "2",
        dev: "5",
        compliance: "6"
    },
    {
        _id: "7",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 7",
        pdfs:"15",
        services: ["website", "social-media", "branding"],
        url: "www.gpofcu.org",
        status: "Signed",
        pm: "2",
        dev: "5",
        compliance: "6"
    },
    {
        _id: "8",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 8",
        pdfs:"15",
        services: ["website", "social-media", "branding"],
        url: "www.gpofcu.org",
        status: "Signed",
        pm: "2",
        dev: "5",
        compliance: "6"
    },
    {
        _id: "9",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 9",
        pdfs:"15",
        services: ["website", "social-media", "branding"],
        url: "www.gpofcu.org",
        status: "Signed",
        pm: "2",
        dev: "5",
        compliance: "6"
    },
    {
        _id: "10",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 10",
        pdfs:"15",
        services: ["website", "social-media", "branding"],
        url: "www.gpofcu.org",
        status: "Signed",
        pm: "2",
        dev: "5",
        compliance: "6"
    },
    {
        _id: "11",
        finalChangesDate: "2019-02-05",
        goLiveDate: "2019-02-11",
        name: "CU 11",
        pdfs:"15",
        services: ["website", "social-media", "branding"],
        url: "www.gpofcu.org",
        status: "Signed",
        pm: "2",
        dev: "5",
        compliance: "6"
    },
];

export default customers;