export default {
//  Customer Actions //
  LOAD_CUSTOMERS_SUCCESS: 'LOAD_CUSTOMERS_SUCCESS',
  LOAD_CUSTOMERS_FAILED: 'LOAD_CUSTOMERS_FAILED',
  CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
  CREATE_CUSTOMER_FAILED: 'CREATE_CUSTOMER_FAILED',
  UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
  UPDATE_CUSTOMER_FAILED: 'UPDATE_CUSTOMER_FAILED',
  DELETE_CUSTOMER_SUCCESS: 'DELETE_CUSTOMER_SUCCESS',
  DELETE_CUSTOMER_FAILED: 'DELETE_CUSTOMER_FAILED',


  // User Actions
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',
  LOAD_USERS_FAILED: 'LOAD_USERS_FAILED',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

  // NOTIFICATIONs
  LOAD_NOTIFICATIONS_SUCCESS: null,
  LOAD_NOTIFICATIONS_FAILED: null,

  // NOTIFICATIONs
  LOAD_FOLDERS_SUCCESS: 'LOAD_FOLDERS_SUCCESS',
  LOAD_FOLDERS_FAILED: 'LOAD_FOLDERS_FAILED',
  ADD_BOARD: 'ADD_BOARD',
  UPDATE_BOARD: 'UPDATE_BOARD',
  DELETE_BOARD: 'DELETE_BOARD',

  // Task
  SET_SIDE_TASK: 'SET_SIDE_TASK',
  UPDATE_SIDE_TASK: 'UPDATE_SIDE_TASK',
};
